version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "America/Argentina/Buenos_Aires"
    open-pull-requests-limit: 5
    assignees:
      - "gonzacha"
    labels:
      - "dependencies"
      - "security"